development:
  adapter: mysql2
  encoding: utf8
  pool: 15
  username: varunk
  host: localhost
  password: Tout@2021
  database: student

development2:
  adapter: mysql2
  encoding: utf8
  pool: 15
  username: varunk
  host: localhost
  password: Tout@2021
  database: student_info
