development:
  adapter: mysql2
  encoding: utf8
  pool: 15
  username: varunk
  host: localhost
  password: Tout@2021
  database: student

development2:
  adapter: sqlserver
  mode: dblib
  host: localhost
  port: 1433
  username: sa
  password: Tout@2018
  database: student_info